SELECT
    p.PAYMENT_ID,
    pd.PAYMENTDETAIL_ID,
    CAST(p.PAYMENTDATE AS TIMESTAMP) AS PAYMENTDATE,
    CAST(p.VALUEDATE AS TIMESTAMP) AS VALUEDATE,
    p.PAIDBY,
    p.RECEIPTNO,
    p.AMOUNT AS PAYMENT_AMOUNT,
    p.PAYMODE_CT,
    p.AFTYPE,
    p.PAYGROUP_CT,
    p.LOCAL_TIN,
    p.USERID,
    p.COLLECTOR,
    p.STATUS_CT AS PAYMENT_STATUS_CT,
    COALESCE(p.VOID_BV, 0) AS VOID_BV,
    COALESCE(p.PROV_BV, 0) AS PROV_BV,
    pd.AMOUNTPAID,
    pd.ITAXTYPE_CT AS PAYMENTDETAIL_ITAXTYPE_CT,
    pd.CASETYPE_CT,
    pd.STATUS_CT AS PAYMENTDETAIL_STATUS_CT,
    pd.SOURCEID,
    pd.SOURCE_CT,
    pd.FUNDTYPE_CT,
    pd.RECEIPTITEMORDER,
    pd.UNIT,
    opr.ITAXTYPE_CT AS RATE_ITAXTYPE_CT,
    opr.OPGROUP,
    opr.OPSUBGROUP,
    opr.DESCRIPTION AS RATE_DESCRIPTION,
    opr.RATE,
    tax.CODE AS TAX_CODE,
    tax.DESCRIPTION AS TAX_DESCRIPTION,
    tax.IGROUP AS TAX_GROUP,
    tax.SUBGROUP AS TAX_SUBGROUP,
    tax.MAINGROUP AS TAX_MAIN_GROUP,
    tax.FUNDTYPE_CT AS TAX_FUNDTYPE_CT
FROM PAYMENT p
INNER JOIN PAYMENTDETAIL pd
    ON p.PAYMENT_ID = pd.PAYMENT_ID
LEFT JOIN T_OTHERPAYMENTRATE opr
    ON pd.SOURCEID = opr.OPRATE_ID
LEFT JOIN T_ITAXTYPE tax
    ON opr.ITAXTYPE_CT = tax.CODE
WHERE COALESCE(p.VOID_BV, 0) = 0
  AND pd.FUNDTYPE_CT = 'GF'
