CREATE TABLE IF NOT EXISTS trust_fund_payment (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATE DATE NULL,
    NAME VARCHAR(150) NULL,
    RECEIPT_NO VARCHAR(50) NULL,
    CASHIER VARCHAR(50) NULL,
    TYPE_OF_RECEIPT VARCHAR(20) NULL,
    BUILDING_PERMIT_FEE DECIMAL(15,2) DEFAULT 0.00,
    LOCAL_80_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    TRUST_FUND_15_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    NATIONAL_5_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    LIVESTOCK_DEV_FUND DECIMAL(15,2) DEFAULT 0.00,
    LOCAL_80_PERCENT_LIVESTOCK DECIMAL(15,2) DEFAULT 0.00,
    NATIONAL_20_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    DIVING_FEE DECIMAL(15,2) DEFAULT 0.00,
    LOCAL_40_PERCENT_DIVE_FEE DECIMAL(15,2) DEFAULT 0.00,
    FISHERS_30_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    BRGY_30_PERCENT DECIMAL(15,2) DEFAULT 0.00,
    ELECTRICAL_FEE DECIMAL(15,2) DEFAULT 0.00,
    ZONING_FEE DECIMAL(15,2) DEFAULT 0.00,
    PAYMENT_STATUS_CT VARCHAR(20) NULL,
    IS_CANCELLED TINYINT(1) DEFAULT 0,
    COMMENTS TEXT NULL,
    TOTAL DECIMAL(15,2) GENERATED ALWAYS AS (
        COALESCE(BUILDING_PERMIT_FEE, 0) +
        COALESCE(ELECTRICAL_FEE, 0) +
        COALESCE(ZONING_FEE, 0) +
        COALESCE(LIVESTOCK_DEV_FUND, 0) +
        COALESCE(DIVING_FEE, 0)
    ) STORED
);

DROP VIEW IF EXISTS trust_fund_payment_main_view;

CREATE VIEW trust_fund_payment_main_view AS
SELECT
    tf.ID,
    tf.ID AS PAYMENT_ID,
    tf.DATE,
    tf.NAME,
    tf.RECEIPT_NO,
    tf.CASHIER,
    tf.TYPE_OF_RECEIPT,
    tf.PAYMENT_STATUS_CT,
    tf.IS_CANCELLED,
    tf.COMMENTS,
    tf.TOTAL
FROM trust_fund_payment tf;
