SELECT
    CAST(p.PAYMENTDATE AS DATE) AS "DATE",
    p.PAIDBY AS "NAME",
    p.RECEIPTNO AS "RECEIPT_NO",
    COALESCE(NULLIF(p.COLLECTOR, ''), p.USERID) AS "CASHIER",
    p.AFTYPE AS "TYPE_OF_RECEIPT",
    p.STATUS_CT AS "PAYMENT_STATUS_CT",
    CASE WHEN p.STATUS_CT = 'CNL' THEN 1 ELSE 0 END AS "IS_CANCELLED",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'PFB' THEN pd.AMOUNTPAID ELSE 0 END), 0), 2) AS "BUILDING_PERMIT_FEE",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'PFB' THEN pd.AMOUNTPAID * 0.80 ELSE 0 END), 0), 2) AS "LOCAL_80_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'PFB' THEN pd.AMOUNTPAID * 0.15 ELSE 0 END), 0), 2) AS "TRUST_FUND_15_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'PFB' THEN pd.AMOUNTPAID * 0.05 ELSE 0 END), 0), 2) AS "NATIONAL_5_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFL' THEN pd.AMOUNTPAID ELSE 0 END), 0), 2) AS "LIVESTOCK_DEV_FUND",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFL' THEN pd.AMOUNTPAID * 0.80 ELSE 0 END), 0), 2) AS "LOCAL_80_PERCENT_LIVESTOCK",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFL' THEN pd.AMOUNTPAID * 0.20 ELSE 0 END), 0), 2) AS "NATIONAL_20_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFD' THEN pd.AMOUNTPAID ELSE 0 END), 0), 2) AS "DIVING_FEE",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFD' THEN pd.AMOUNTPAID * 0.40 ELSE 0 END), 0), 2) AS "LOCAL_40_PERCENT_DIVE_FEE",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFD' THEN pd.AMOUNTPAID * 0.30 ELSE 0 END), 0), 2) AS "FISHERS_30_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'IFD' THEN pd.AMOUNTPAID * 0.30 ELSE 0 END), 0), 2) AS "BRGY_30_PERCENT",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'EP' THEN pd.AMOUNTPAID ELSE 0 END), 0), 2) AS "ELECTRICAL_FEE",
    ROUND(COALESCE(SUM(CASE WHEN opr.ITAXTYPE_CT = 'ZLC' THEN pd.AMOUNTPAID ELSE 0 END), 0), 2) AS "ZONING_FEE",
    NULL AS "COMMENTS"
FROM PAYMENT p
INNER JOIN PAYMENTDETAIL pd
    ON p.PAYMENT_ID = pd.PAYMENT_ID
INNER JOIN T_OTHERPAYMENTRATE opr
    ON pd.SOURCEID = opr.OPRATE_ID
WHERE pd.FUNDTYPE_CT = 'TF'
  AND COALESCE(p.VOID_BV, 0) = 0
  AND opr.ITAXTYPE_CT IN ('PFB', 'EP', 'ZLC', 'IFL', 'IFD')
