WITH owner_per_property AS (
    SELECT
        po.PROP_ID,
        LIST(tx.OWNERNAME, ' / ') AS OWNERNAME
    FROM PROPERTYOWNER po
    JOIN TAXPAYER tx
        ON tx.LOCAL_TIN = po.LOCAL_TIN
    GROUP BY po.PROP_ID
),
liability_per_property AS (
    SELECT
        rl.PROP_ID,
        LIST(tx.OWNERNAME, ' / ') AS OWNERNAME
    FROM RPTLIABILITY rl
    JOIN TAXPAYER tx
        ON tx.LOCAL_TIN = rl.LOCAL_TIN
    GROUP BY rl.PROP_ID
),
rpt_base AS (
    SELECT
        p.PAYMENT_ID,
        CAST(p.PAYMENTDATE AS DATE) AS PAY_DATE,
        p.PAIDBY,
        p.RECEIPTNO,
        p.USERID AS CASHIER,
        p.STATUS_CT AS PAYMENT_STATUS_CT,
        COALESCE(p.VOID_BV, 0) AS IS_VOID,
        p.AMOUNT AS PAYMENT_TOTAL_AMOUNT,
        pcd.TAXTRANS_ID,
        pcd.ITAXTYPE_CT,
        pcd.CASETYPE_CT,
        pcd.TAXYEAR,
        pcd.AMOUNT,
        pcd.CLASSCODE_CT,
        pcd.PROPERTYKIND_CT,
        ra.PROP_ID,
        ra.TDNO,
        pr.PINNO,
        pr.BARANGAY_CT,
        pr.MUNICIPAL_ID,
        pr.PROVINCE_CT
    FROM PAYMENT p
    JOIN PAYMENTCLASSDETAIL pcd
        ON p.PAYMENT_ID = pcd.PAYMENT_ID
    LEFT JOIN RPTASSESSMENT ra
        ON ra.TAXTRANS_ID = pcd.TAXTRANS_ID
    LEFT JOIN PROPERTY pr
        ON pr.PROP_ID = ra.PROP_ID
    WHERE p.PAYMENTDATE >= '__START_DATE__'
      AND p.PAYMENTDATE < '__END_DATE__'
),
rpt_enriched AS (
    SELECT
        b.PAY_DATE,
        b.PAIDBY,
        COALESCE(op.OWNERNAME, lp.OWNERNAME) AS OWNERNAME,
        b.RECEIPTNO,
        b.CASHIER,
        b.PAYMENT_STATUS_CT,
        b.IS_VOID,
        b.PAYMENT_TOTAL_AMOUNT,
        b.ITAXTYPE_CT,
        b.CASETYPE_CT,
        b.TAXYEAR,
        b.AMOUNT,
        COALESCE(
            NULLIF(TRIM(b.PINNO), ''),
            NULLIF(TRIM(b.TDNO), ''),
            CAST(b.TAXTRANS_ID AS VARCHAR(30))
        ) AS PROPERTY_KEY,
        COALESCE(
            NULLIF(TRIM(b.PINNO), ''),
            NULLIF(TRIM(b.TDNO), '')
        ) AS PIN,
        tb.DESCRIPTION AS NAME_OF_BARANGAY,
        CASE
            WHEN TRIM(pk.DESCRIPTION) = 'IMPRVMNTS' THEN NULL
            ELSE TRIM(pk.DESCRIPTION) || '-' ||
                CASE TRIM(b.CLASSCODE_CT)
                    WHEN 'A' THEN 'AGRICULTURAL'
                    WHEN 'C' THEN 'COMMERCIAL'
                    WHEN 'R' THEN 'RESIDENTIAL'
                    WHEN 'I' THEN 'INDUSTRIAL'
                    WHEN 'M' THEN 'MINERAL'
                    WHEN 'T' THEN 'TIMBERLAND'
                    WHEN 'S' THEN 'SPECIAL'
                    ELSE TRIM(b.CLASSCODE_CT)
                END
        END AS PROPERTY_CLASSIFICATION
    FROM rpt_base b
    LEFT JOIN owner_per_property op
        ON op.PROP_ID = b.PROP_ID
    LEFT JOIN liability_per_property lp
        ON lp.PROP_ID = b.PROP_ID
    LEFT JOIN T_BARANGAY tb
        ON tb.CODE = b.BARANGAY_CT
       AND tb.MUNICIPAL_ID = b.MUNICIPAL_ID
       AND tb.PROVINCE_CT = b.PROVINCE_CT
    LEFT JOIN T_PROPERTYKIND pk
        ON pk.CODE = b.PROPERTYKIND_CT
),
rpt_agg AS (
    SELECT
        MIN(e.PAY_DATE) AS "DATE",
        MAX(e.PAIDBY) AS "PAID_BY",
        MAX(e.OWNERNAME) AS "NAME_OF_TAXPAYER",
        CASE
            WHEN MIN(e.TAXYEAR) = MAX(e.TAXYEAR)
                THEN CAST(MIN(e.TAXYEAR) AS VARCHAR(4))
            ELSE CAST(MIN(e.TAXYEAR) AS VARCHAR(4)) || '-' || CAST(MAX(e.TAXYEAR) AS VARCHAR(4))
        END AS "PERIOD_COVERED",
        MAX(e.PIN) AS "PIN",
        e.RECEIPTNO AS "OR_NO",
        e.NAME_OF_BARANGAY AS "NAME_OF_BARANGAY",

        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_CURRENT_YEAR",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_CURRENT_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'DED' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_DISCOUNTS",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.TAXYEAR = __REPORT_YEAR__ AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) AS "BASIC_IMMEDIATE",

        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR = __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_PRECEDING_YEAR",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR = __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_PRECEDING_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR < __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_PRIOR_YEARS",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR < __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "BASIC_PRIOR_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) AS "BASIC_TOTAL",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'BSC' AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) * 0.25 AS "BASIC_25_SHARE",

        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_CURRENT_YEAR",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_CURRENT_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'DED' AND e.TAXYEAR = __REPORT_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_DISCOUNTS",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.TAXYEAR = __REPORT_YEAR__ AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) AS "SEF_IMMEDIATE",

        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR = __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_PRECEDING_YEAR",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR = __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_PRECEDING_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'REG' AND e.TAXYEAR < __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_PRIOR_YEARS",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT = 'PEN' AND e.TAXYEAR < __PREVIOUS_YEAR__ THEN e.AMOUNT ELSE 0 END) AS "SEF_PRIOR_PENALTIES",
        SUM(CASE WHEN e.ITAXTYPE_CT = 'SEF' AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) AS "SEF_TOTAL",

        SUM(CASE WHEN e.ITAXTYPE_CT IN ('BSC', 'SEF') AND e.CASETYPE_CT IN ('REG', 'PEN', 'DED') THEN e.AMOUNT ELSE 0 END) AS "BASIC_AND_SEF",

        e.PROPERTY_CLASSIFICATION AS "PROPERTY_CLASSIFICATION",
        MAX(e.CASHIER) AS "CASHIER",
        MAX(e.PAYMENT_STATUS_CT) AS "PAYMENT_STATUS_CT",
        MAX(e.IS_VOID) AS "IS_VOID",
        CASE WHEN MAX(e.PAYMENT_STATUS_CT) = 'CNL' THEN 1 ELSE 0 END AS "IS_CANCELLED",
        CASE
            WHEN MAX(e.IS_VOID) = 1 OR MAX(e.PAYMENT_STATUS_CT) = 'CNL' THEN 0
            ELSE 1
        END AS "INCLUDE_IN_REPORT",
        MAX(e.PAYMENT_TOTAL_AMOUNT) AS "PAYMENT_TOTAL_AMOUNT"
    FROM rpt_enriched e
    GROUP BY
        e.RECEIPTNO,
        e.PROPERTY_KEY,
        e.NAME_OF_BARANGAY,
        e.PROPERTY_CLASSIFICATION
)
SELECT *
FROM rpt_agg
WHERE (COALESCE("BASIC_TOTAL", 0) <> 0 OR COALESCE("SEF_TOTAL", 0) <> 0)
  AND COALESCE("PROPERTY_CLASSIFICATION", '') <> ''
ORDER BY "DATE", "OR_NO", "PROPERTY_CLASSIFICATION", "PIN";
