export const procurementConfigs = {
  "disbursement-vouchers": {
    type: "disbursement-vouchers",
    title: "Disbursement Voucher",
    shortTitle: "DV",
    description: "Prepare, track, and print disbursement vouchers for payment processing.",
    documentNoLabel: "DV No.",
    referenceNoLabel: "Obligation Request No.",
    partyLabel: "Payee",
    officeLabel: "Office / Unit",
    extraFields: [
      { key: "tin_employee_no", label: "TIN / Employee No." },
      { key: "approved_budget", label: "Approved Budget" },
    ],
  },
  "obligation-requests": {
    type: "obligation-requests",
    title: "Obligation Request",
    shortTitle: "OR",
    description: "Manage obligation requests before procurement and payment release.",
    documentNoLabel: "OR No.",
    referenceNoLabel: "Fund Source Ref.",
    partyLabel: "Requested By",
    officeLabel: "Requesting Office",
    extraFields: [
      { key: "fund_cluster", label: "Fund Cluster" },
      { key: "expense_class", label: "Expense Class" },
    ],
  },
  "requisition-issue-slips": {
    type: "requisition-issue-slips",
    title: "Requisition and Issue Slip",
    shortTitle: "RIS",
    description: "Track requested and issued inventory or supplies.",
    documentNoLabel: "RIS No.",
    referenceNoLabel: "Stock Ref. No.",
    partyLabel: "Requested By",
    officeLabel: "Office / Department",
    extraFields: [
      { key: "inventory_type", label: "Inventory Type" },
      { key: "issue_to", label: "Issue To" },
    ],
  },
  "purchase-requests": {
    type: "purchase-requests",
    title: "Purchase Request",
    shortTitle: "PR",
    description: "Create and approve purchase requests before canvass and ordering.",
    documentNoLabel: "PR No.",
    referenceNoLabel: "Reference No.",
    partyLabel: "Requested By",
    officeLabel: "Requesting Office",
    extraFields: [
      { key: "purpose", label: "Purpose" },
      { key: "requested_mode", label: "Requested Mode" },
    ],
  },
  "purchase-orders": {
    type: "purchase-orders",
    title: "Purchase Order",
    shortTitle: "PO",
    description: "Maintain purchase orders, supplier data, and award details.",
    documentNoLabel: "PO No.",
    referenceNoLabel: "PR No.",
    partyLabel: "Supplier",
    officeLabel: "End-User Office",
    extraFields: [
      { key: "supplier_tin", label: "Supplier TIN" },
      { key: "delivery_term", label: "Delivery Term" },
    ],
  },
  "job-orders": {
    type: "job-orders",
    title: "Job Order",
    shortTitle: "JO",
    description: "Record service-based job orders and contractor execution details.",
    documentNoLabel: "JO No.",
    referenceNoLabel: "Contract Ref.",
    partyLabel: "Contractor",
    officeLabel: "Implementing Office",
    extraFields: [
      { key: "contract_duration", label: "Contract Duration" },
      { key: "work_location", label: "Work Location" },
    ],
  },
  "job-order-requests": {
    type: "job-order-requests",
    title: "Job Order Request",
    shortTitle: "JOR",
    description: "Handle incoming requests for job order procurement and services.",
    documentNoLabel: "JOR No.",
    referenceNoLabel: "Requested Work Ref.",
    partyLabel: "Requester",
    officeLabel: "Requesting Office",
    extraFields: [
      { key: "work_type", label: "Work Type" },
      { key: "target_completion", label: "Target Completion" },
    ],
  },
  "abstract-of-canvass": {
    type: "abstract-of-canvass",
    title: "Abstract of Canvass",
    shortTitle: "AOC",
    description: "Compare quotations and identify the recommended winning offer.",
    documentNoLabel: "AOC No.",
    referenceNoLabel: "PR No.",
    partyLabel: "Winning Bidder",
    officeLabel: "Procuring Unit",
    extraFields: [
      { key: "canvass_date", label: "Canvass Date" },
      { key: "canvass_committee", label: "Canvass Committee" },
    ],
  },
  "pr-recommendations": {
    type: "pr-recommendations",
    title: "PR Recommendation",
    shortTitle: "PRR",
    description: "Document recommendation outcomes tied to purchase requests.",
    documentNoLabel: "PR Recommendation No.",
    referenceNoLabel: "PR No.",
    partyLabel: "Recommended Supplier",
    officeLabel: "Recommending Office",
    extraFields: [
      { key: "recommendation_basis", label: "Recommendation Basis" },
      { key: "committee_name", label: "Committee / BAC" },
    ],
  },
};

export const procurementList = Object.values(procurementConfigs);
